name: anchore-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  alpine-anchore-analysis:
    uses: paniclobster/github-workflows/.github/workflows/docker-anchore-analysis.yaml@main
    with:
      docker_build_context: ./alpine
      docker_image_name: paniclobster/helm-packager
  debian-anchore-analysis:
    uses: paniclobster/github-workflows/.github/workflows/docker-anchore-analysis.yaml@main
    with:
      docker_build_context: ./debian
      docker_image_name: paniclobster/helm-packager
