name: build-publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  alpine-build-publish:
    uses: paniclobster/github-workflows/.github/workflows/docker-build-publish.yaml@main
    with:
      docker_build_context: ./alpine
      docker_image_name: public.ecr.aws/paniclobster/devcontainer-base
      docker_image_tag_suffix: -alpine
    secrets:
      docker_login_registry: public.ecr.aws
      docker_login_username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
      docker_login_password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
  debian-build-publish:
    uses: paniclobster/github-workflows/.github/workflows/docker-build-publish.yaml@main
    with:
      docker_build_context: ./debian
      docker_image_name: public.ecr.aws/paniclobster/devcontainer-base
    secrets:
      docker_login_registry: public.ecr.aws
      docker_login_username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
      docker_login_password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
