name: build-publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  alpine-build-publish:
    uses: paniclobster/github-workflows/.github/workflows/docker-build-publish.yaml@main
    with:
      docker_build_context: ./alpine
      docker_image_name: ghcr.io/${{ github.repository }}
      docker_image_tag_suffix: -alpine
    secrets:
      docker_login_registry: ghcr.io
      docker_login_username: ${{ github.actor }}
      docker_login_password: ${{ secrets.GITHUB_TOKEN }}
  debian-build-publish:
    uses: paniclobster/github-workflows/.github/workflows/docker-build-publish.yaml@main
    with:
      docker_build_context: ./debian
      docker_image_name: ghcr.io/${{ github.repository }}
    secrets:
      docker_login_registry: ghcr.io
      docker_login_username: ${{ github.actor }}
      docker_login_password: ${{ secrets.GITHUB_TOKEN }}
