name: build-publish

env:
  DOCKER_IMAGE_NAME: paniclobster/devcontainer-workspace

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.2
      - name: Get release version
        id: get_release_version
        run: echo ::set-output name=tags::${GITHUB_REF#refs/*/v}
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          tags: ${{ steps.get_release_version.outputs.tags }},latest
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
