name: dive-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  alpine-dive-analysis:
    uses: paniclobster/github-workflows/.github/workflows/docker-dive-analysis.yaml@main
    with:
      docker_build_context: ./alpine
      docker_image_name: paniclobster/devcontainer-base
  debian-dive-analysis:
    uses: paniclobster/github-workflows/.github/workflows/docker-dive-analysis.yaml@main
    with:
      docker_build_context: ./debian
      docker_image_name: paniclobster/devcontainer-base
